tap "adoptopenjdk/openjdk"
tap "aquasecurity/trivy"
tap "aws/tap"
tap "fabianishere/personal"
tap "github/gh"
tap "golangci/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/services"
tap "itchyny/rexdep"
tap "itchyny/tap"
tap "kayac/tap"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "rhysd/actionlint", "https://github.com/rhysd/actionlint"

brew "angband"
brew "aquasecurity/trivy/trivy"
brew "asciidoctor"
brew "awscli"
brew "awslogs"
brew "bash"
brew "bat"
brew "cfssl"
brew "cocoapods"
brew "container-diff"
brew "coreutils"
brew "ctags"
brew "ctop"
brew "curl"
brew "docker-credential-helper-ecr"
brew "entr"
brew "envchain"
brew "eza"
brew "fabianishere/personal/pam_reattach"
brew "fd"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "go"
brew "golangci/tap/golangci-lint"
brew "graphviz"
brew "grep"
brew "hadolint"
brew "heroku/brew/heroku"
brew "htop"
brew "httpie"
brew "itchyny/tap/mmv"
brew "jq"
brew "kayac/tap/ecspresso"
brew "kubectx"
brew "kubernetes-cli"
brew "lsd"
brew "lv"
brew "massren"
brew "minikube"
brew "mise"
brew "mitmproxy"
brew "mkcert"
brew "neomutt"
brew "neovim"
brew "neovim"
brew "node-build"
brew "nodenv"
brew "nyancat"
brew "percona-toolkit"
brew "perl-build"
brew "plantuml"
brew "poetry", link: false
brew "procs"
brew "protobuf"
brew "pstree"
brew "pwgen"
brew "readline"
brew "rhysd/actionlint/actionlint"
brew "rustup"
brew "shellcheck"
brew "skaffold"
brew "sshuttle"
brew "stern"
brew "terraform"
brew "the_platinum_searcher"
brew "the_platinum_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "urlview"
brew "vim"
brew "w3m"
brew "wget"
brew "zplug"
brew "zsh"

# cask "1password"
cask "1password-cli"
cask "adoptopenjdk11"
cask "authy"
cask "anki"
# cask "aws-vpn-client"
cask "choosy"
cask "discord"
cask "docker"
# cask "dropbox"
cask "dungeon-crawl-stone-soup-console"
cask "firefox-developer-edition"
cask "font-cascadia-code"
cask "font-envy-code-r"
cask "font-fira-code"
cask "gimp"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "google-drive"
cask "google-japanese-ime"
cask "hammerspoon"
cask "iterm2"
cask "karabiner-elements"
cask "licecap"
cask "logitech-options"
cask "slack"
cask "typora"
cask "visual-studio-code"
cask "workflowy"
# cask "zoom"
cask "font-fira-code-nerd-font"
cask "shureplus-motiv"
cask "kindle"
cask "font-cousine-nerd-font"
cask "font-udev-gothic-nf"
cask "spotify"
case "rancher"

brew "mas"
mas "Dato", id: 1470584107
mas "RunCat", id: 1429033973
# mas "Slack for Desktop", id: 803453959
mas "Input Source Pro", id: 1537056428

cask "switchkey"
cask "showyedge"

brew "gpg"
