#!/bin/sh

set -e

cd $(dirname $0)
base=$(pwd)

echo '---> Making symlinks'

for dotfile in .*; do
    case $dotfile in
        .|..|.git|.gitmodules)
            ;;
        *)
            ( cd && ln -s -v $base/$dotfile ) || true
            ;;
    esac

done

touch ~/.tmux.local.conf

echo '---> Updating Git submodules'

git submodule update --init

echo '---> Installing Vim bundles'

if [ -t 0 ]; then
    vim -e +PlugInstall +qall!
elif [ "$(uname)" = Darwin ]; then
    script dotfiles-setup.log vim +PlugInstall '+qall!'
else
    script -c 'vim -e +PlugInstall +qall!'
fi

setup_os=setup.$(uname -s)
if [ -e "$setup_os" ]; then
    . $setup_os
fi
