#!/bin/sh

set -e

cd $(dirname $0)
base=$(pwd)

echo '---> Making symlinks'

for dotfile in .*; do
    case $dotfile in
        .|..|.git|.gitmodules)
            ;;
        *)
            ( cd && ln -s -v $base/$dotfile ) || true
            ;;
    esac

done

echo '---> Updating Git submodules'

git submodule update --init

echo '---> Installing Vim bundles'

if [ -t 0 ]; then
    vim -e +BundleInstall +qall!
elif [ "$(uname)" = Darwin ]; then
    script dotfiles-setup.log vim -e +BundleInstall '+qall!'
else
    script -c 'vim -e +BundleInstall +qall!'
fi
